import 'package:feather_icons/feather_icons.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:polzet_mobile_app/data/internet/connection_wrapper.dart';
import 'package:provider/provider.dart';

import '../../../../api/api_service.dart';
import '../../../../api/model/country/country_model.dart';
import '../../../../core/constants/app_colors.dart';
import '../../../../core/constants/app_images.dart';
import '../../../../core/constants/app_strings.dart';
import '../../../../mixins/utility_mixins.dart';
import '../../../../provider/user_provider.dart';
import '../../../common widgets/country code/custom_country_code.dart';
import '../../../common widgets/text field/primary_textfield.dart';
import '../../../common widgets/button/auth_button.dart';
import '../../../common widgets/custom_card.dart';
import '../../../common widgets/custom_text_styles.dart';
import '../email verify/email_verify_import.dart';
import '../forgot password/forgot_password_import.dart';
part 'login_screen.dart';