// ignore_for_file: undefined_hidden_name
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:dio/dio.dart';
import 'package:dotted_border/dotted_border.dart';
import 'package:feather_icons/feather_icons.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:glass/glass.dart';
import 'package:image_cropper/image_cropper.dart';
import 'package:image_picker/image_picker.dart';
import 'package:provider/provider.dart';
import 'package:shimmer/shimmer.dart';
import 'package:wechat_assets_picker/wechat_assets_picker.dart';
import 'package:wechat_camera_picker/wechat_camera_picker.dart';

import '../../../api/api_config.dart';
import '../../../api/services/api_service.dart';
import '../../../api/app_api.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_images.dart';
import '../../../core/constants/app_strings.dart';
import '../../../data/token/shared_preferences.dart';
import '../../../l10n/generated/app_localizations.dart';
import '../../../mixin/utility_mixins.dart';
import '../../../models/country/country_model.dart';
import '../../../models/posts/image/post_image_model.dart';
import '../../../models/posts/post_polls_model.dart';
import '../../../provider/user_provider.dart';
import '../../../widgets/button/back_button.dart';
import '../../../widgets/card/user_things_card.dart';
import '../../../widgets/country code/custom_country_code.dart';
import '../../../widgets/custom_card.dart';
import '../../../widgets/custom_text_styles.dart';
import '../../../widgets/loader.dart';
import '../../../widgets/show_toast.dart';
import '../../../widgets/simmer/chase/profile_chase_simmer.dart';
import '../../../widgets/simmer/profile_simmer.dart';
import '../poll/poll_question.dart';
import 'chase/user_chase.dart';
import 'posts/image_posts_list.dart';
import 'posts/questions_posts_list.dart';

part 'user_profile.dart';
part 'edit_profile/edit_profile.dart';