name: polzet_mobile_app
description: A new Flutter project

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  page_transition: ^2.2.1
  google_fonts: ^6.3.3
  flutter_screenutil: ^5.9.3
  provider: ^6.1.5+1
  feather_icons: ^1.2.0
  shared_preferences: ^2.5.4
  dio: ^5.9.0
  curved_navigation_bar: ^1.0.6
  lottie: ^3.3.2

  flutter_localizations:
    sdk: flutter
  fluttertoast: ^9.0.0
  shimmer: ^3.0.0
  icons_plus: ^5.0.0
  http: ^1.6.0
  glass: ^2.0.0+2
  dotted_border: ^3.1.0
  image_cropper: ^11.0.0
  image_picker: ^1.2.1
  wechat_assets_picker: ^10.0.0
  wechat_camera_picker: ^4.4.0
  local_auth: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_app.png"  # Ensure the file exists in this path
  adaptive_icon_background: "#ffffff"  # Background color (you can use an image too)
  adaptive_icon_foreground: "assets/images/ic_app.png"

flutter: 
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/constants
  filename: app_images.dart
